# Generated by Django 4.2.2 on 2023-06-30 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.date(2023, 7, 1)),
        ),
    ]
