# Generated by Django 4.2.2 on 2023-07-03 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_email_profile_password_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
