# Generated by Django 4.2.2 on 2023-07-17 11:27
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.db import migrations

def default_users(apps, schema_editor):
    User.objects.create(username = "Sergey", email="sergey@mail.ru", password = make_password("qwertyuiop12345678"))
    User.objects.create(username="Kirill", email="kirill@mail.ru", password = make_password("qwertyuiop12345678"))
    User.objects.create(username="Olga", email="olgal@mail.ru", password = make_password("qwertyuiop12345678"))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_date_of_birth'),
    ]

    operations = [migrations.RunPython(default_users)]
