# Generated by Django 4.2.2 on 2023-07-18 14:32
from django.db import migrations
import datetime

def default_films(apps, schema_editor):
    description1 = "Experienced climber Pam climbs Mount Washington, but decides to turn back, fearing a severe snowstorm. On the way down, she meets a stuck man and takes the liberty to help him. Now they need to get down the mountain before night falls."
    description2 = "A 2008 American military action film directed by Sylvester Stallone, who also acted as a co-author of the script and the performer of the main role. The fourth film in the series is about Vietnam War veteran John Rambo. The release in the cinema of Russia took place on January 24, 2008."
    description3 = "Four-fingered Frankie had to smuggle the stolen diamond from England to the USA to his boss Evie. But instead, the hero finds himself in the epicenter of big trouble. Betting on an underground boxing match, Frankie gets into a cycle of very undesirable events. A complex intrigue unfolds around the hero and his cargo with the participation of many colorful characters of the London underworld — a Russian gangster, three hapless robbers, a cunning boxer and a gloomy bully of a formidable mafia. Everyone strives to hit a Big Jackpot alone. And everything ends with an unexpected and witty ending."
    Films = apps.get_model('inopolis', 'Film')
    IS = Films.objects.create(title="Infinite Storm", description=description1, rating="R", director="Malgorzata Shumowska", producer="Michal Englert", writer="Taya Gagne", release_date_theaters=datetime.date(2022,3,25), release_date_streaming=datetime.date(2023, 7, 17), data='inopolis/video/beskonecnaya_burya.mp4', picture='inopolis/img/pictures/infinite_storm.jpg')
    IS.genre.create(name="Drama")
    R = Films.objects.create(title="Rambo IV", description=description2, rating="G", director="Sylvester Stallone", producer="Kevin King Templeton, Avi Lerner", writer="Art Monterastelli, Sylvester Stallone, David Morell", release_date_theaters=datetime.date(2008, 1, 23), release_date_streaming=datetime.date(2023, 7, 17), data='inopolis/video/rambo4.mp4', picture='inopolis/img/pictures/rambo4.jpg')
    R.genre.create(name="Action")
    S = Films.objects.create(title="Snatch", description=description3, rating="PG", director="Guy Ritchie", producer="Matthew Vaughn, Michael Dreyer, Stephen Marks", writer="Mel Brooks, Thomas Mian", release_date_theaters=datetime.date(2005, 12, 16), release_date_streaming=datetime.date(2023, 7, 17), data='inopolis/video/snatch.mp4', picture='inopolis/img/pictures/snatch.jpg')
    S.genre.create(name='Comedy')

class Migration(migrations.Migration):

    dependencies = [
        ('inopolis', '0002_film_picture_alter_film_data'),
    ]

    operations = [migrations.RunPython(default_films)]
